class Book {
  final String image;
  final double price;
  final String title;
  final String author;
  final String description;
  final double rate;
  final int pages;
  final int published;
  final String? id;
  final int quantity;

  Book({
    required this.image,
    required this.price,
    required this.title,
    required this.author,
    required this.description,
    required this.pages,
    required this.published,
    required this.rate,
    this.id,
    this.quantity = 1,
  });

  Book copyWith({
    String? image,
    double? price,
    String? title,
    String? author,
    String? description,
    double? rate,
    int? pages,
    int? published,
    String? id,
    int? quantity,
  }) {
    return Book(
      image: image ?? this.image,
      price: price ?? this.price,
      title: title ?? this.title,
      author: author ?? this.author,
      description: description ?? this.description,
      rate: rate ?? this.rate,
      pages: pages ?? this.pages,
      published: published ?? this.published,
      id: id ?? this.id,
      quantity: quantity ?? this.quantity,
    );
  }

  factory Book.fromJson(Map<String, dynamic> json) {
    return Book(
      image: json['image'] ?? '',
      price: (json['price'] ?? 0).toDouble(),
      title: json['title'] ?? '',
      author: json['author'] ?? '',
      description: json['description'] ?? '',
      rate: (json['rate'] ?? 0).toDouble(),
      pages: json['pages'] ?? 0,
      published: json['published'] ?? 0,
      id: json['id'] as String?,
      quantity: json['quantity'] ?? 1,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'image': image,
      'price': price,
      'title': title,
      'author': author,
      'description': description,
      'rate': rate,
      'pages': pages,
      'published': published,
      'id': id,
      'quantity': quantity,
    };
  }
}

final List<Book> books = [
  Book(
    image: 'https://www.simbasible.com/wp-content/uploads/2020/12/22-8-1024x1541.jpg',
    price: 12.99,
    rate: 4.28,
    pages: 671 ,
    published: 1866,
    title: 'Crime and Punishment',
    author: 'Fyodor Dostoevsky',
    description: 'Raskolnikov, a destitute and desperate former student, wanders through the slums of St Petersburg and commits a random murder without remorse or regret. He imagines himself to be a great man, a Napoleon: acting for a higher purpose beyond conventional moral law. But as he embarks on a dangerous game of cat and mouse with a suspicious police investigator, Raskolnikov is pursued by the growing voice of his conscience and finds the noose of his own guilt tightening around his neck. Only Sonya, a downtrodden sex worker, can offer the chance of redemption.',
  ),
  Book(
    image: 'https://th.bing.com/th/id/R.65701b3ce162a40c71d732729bd4b063?rik=DZ3x2EkWmjb%2fZQ&riu=http%3a%2f%2f2.bp.blogspot.com%2f_z_SzlnEtJ7A%2fTE35js1Q7rI%2fAAAAAAAAAH8%2fCXgvalCRKIU%2fs1600%2fthebrotherskaramazov.jpg&ehk=R5cnmgz%2fITHbRH%2bpBx9cvWftbcufoU%2bEc3IcWm7sLB0%3d&risl=&pid=ImgRaw&r=0',
    price: 14.99,
    rate: 4.38,
    pages: 796,
    published: 1880,
    title: 'The Brothers Karamazov',
    author: ' Fyodor Dostoevsky',
    description: 'The Brothers Karamazov is a murder mystery, a courtroom drama, and an exploration of erotic rivalry in a series of triangular love affairs involving the “wicked and sentimental” Fyodor Pavlovich Karamazov and his three sons―the impulsive and sensual Dmitri; the coldly rational Ivan; and the healthy, red-cheeked young novice Alyosha. Through the gripping events of their story, Dostoevsky portrays the whole of Russian life, is social and spiritual striving, in what was both the golden age',
  ),
  Book(
    image: 'https://weltbild.scene7.com/asset/vgw/the-idiot-190020969.jpg',
    price: 10.50,
     rate: 4.21,
    pages: 671 ,
    published: 1869,
    title: 'The Idiot',
    author: 'Fyodor Dostoevsky',
    description: 'Returning to Russia from a sanitarium in Switzerland, the Christ-like epileptic Prince Myshkin finds himself enmeshed in a tangle of love, torn between two women—the notorious kept woman Nastasya and the pure Aglaia—both involved, in turn, with the corrupt, money-hungry Ganya. In the end, Myshkin’s honesty, goodness, and integrity are shown to be unequal to the moral emptiness of those around him. In her revision of the Garnett translation, Anna Brailovsky has corrected inaccuracies wrought by Garnett’s drastic anglicization of the novel, restoring as much as possible the syntactical structure of the original story.',
  ),
  Book(
    image: 'https://th.bing.com/th/id/OIP.wZYeevNc9QgOZ0tpmU3OAgAAAA?rs=1&pid=ImgDetMain',
    price: 11.25,
     rate: 4.30,
    pages: 733 ,
    published: 1872,
    title: 'Demons',
    author: 'Fyodor Dostoevsky',
    description: 'Inspired by the true story of a political murder that horrified Russians in 1869, Fyodor Dostoevsky conceived of Demons as a "novel-pamphlet" in which he would say everything about the plague of materialist ideology that he saw infecting his native land. What emerged was a prophetic and ferociously funny masterpiece of ideology and murder in pre-revolutionary Russia.',
  ),
  Book(
    image: 'https://m.media-amazon.com/images/I/91VHhTNH12L._SL1500_.jpg',
    price: 13.49,
    rate: 4.28,
    pages: 671 ,
    published: 1967,
    title: 'The Master and Margarita',
    author: 'Mikhail Bulgakov',
    description: 'An audacious revision of the stories of Faust and Pontius Pilate, The Master and Margarita is recognized as one of the essential classics of modern Russian literature. The novels vision of Soviet life in the 1930s is so ferociously accurate that it could not be published during its authors lifetime and appeared only in a censored edition in the 1960s. Its truths are so enduring that its language has become part of the common Russian speech.',
  ),
  Book(
    image: 'https://m.media-amazon.com/images/I/91FXycpulgL._AC_UF1000,1000_QL80_.jpg',
    price: 9.99,
    rate: 4.16,
    pages: 1392  ,
    published: 1869,
    title: 'War and Peace',
    author: 'Leo Tolstoy.',
    description: 'War and Peace broadly focuses on Napoleon’s invasion of Russia in 1812 and follows three of the most well-known characters in literature: Pierre Bezukhov, the illegitimate son of a count who is fighting for his inheritance and yearning for spiritual fulfillment; Prince Andrei Bolkonsky, who leaves his family behind to fight in the war against Napoleon; and Natasha Rostov, the beautiful young daughter of a nobleman who intrigues both men.',
  ),
  Book(
    image: 'https://m.media-amazon.com/images/I/71O6QVa5X+L._SL1500_.jpg',
    price: 15.99,
    rate: 4.00,
    pages: 244 ,
    published: 1862,
    title: 'Fathers and Sons',
    author: 'Ivan Turgenev',
    description: 'Bazarov—a gifted, impatient, and caustic young man—has journeyed from school to the home of his friend Arkady Kirsanov. But soon Bazarov’s outspoken rejection of authority and social conventions touches off quarrels, misunderstandings, and romantic entanglements that will utterly transform the Kirsanov household and reflect the changes taking place across all of nineteenth-century Russia.',
  ),
  Book(
    image: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1698856565i/197964528.jpg',
    price: 8.75,
    rate: 3.98,
    pages: 464 ,
    published: 1842,
    title: 'Dead Souls',
    author: 'Nikolai Gogol',
    description: 'Chichikov, a mysterious stranger, arrives in a provincial town and visits a succession of landowners to make each a strange offer. He proposes to buy the names of dead serfs still registered on the census, saving their owners from paying taxes on them, and to use these souls as collateral to re-invent himself as a gentleman. In this ebullient masterpiece, Gogol created a grotesque gallery of human types, from the bear-like Sobakevich to the insubstantial fool Manilov, and, above all, the devilish con man Chichikov. Dead Souls, Russias first major novel, is one of the most unusual works of nineteenth-century fiction and a devastating satire on social hypocrisy.',
  ),
  Book(
    image: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1663546974i/18386.jpg',
    price: 6.49,
    rate: 4.13,
    pages: 86 ,
    published: 1886,
    title: 'The Death of Ivan Ilych',
    author: 'Leo Tolstoy',
    description: 'Hailed as one of the worlds supreme masterpieces on the subject of death and dying, The Death of Ivan Ilyich is the story of a worldly careerist, a high court judge who has never given the inevitability of his dying so much as a passing thought. But one day, death announces itself to him, and to his shocked surprise, he is brought face to face with his own mortality.',
  ),
  Book(
    image: 'https://th.bing.com/th/id/OIP.F5td1ksEX-HjfEM_djzqUwAAAA?rs=1&pid=ImgDetMain',
    price: 17.00,
    rate: 4.16,
    pages: 562 ,
    published: 1899,
    title: 'Resurrection',
    author: 'Leo Tolstoy',
    description: 'Resurrection (1899) is the last of Tolstoys major novels. It tells the story of a noblemans attempt to redeem the suffering his youthful philandering inflicted on a peasant girl who ends up a prisoner in Siberia. Tolstoys vision of redemption, achieved through loving forgiveness and his condemnation of violence, dominate the novel. An intimate, psychological tale of guilt, anger, and forgiveness, Resurrection is at the same time a panoramic description of social life in Russia at the end of the nineteenth century, reflecting its authors outrage at the social injustices of the world in which he lived. This edition, which updates a classic translation, has explanatory notes, and a substantial introduction based on the most recent scholarship in the field.',
  ),
  Book(
    image: 'https://cdn.kobo.com/book-images/2af22cca-0e50-42c4-8f3a-de9f69053a48/1200/1200/False/anna-karenina-movie-tie-in-edition.jpg',
    price: 10.99,
     rate: 4.28,
    pages: 671 ,
    published: 1878,
    title: 'Anna Karenina',
    author: 'Leo Tolstoy',
    description: 'Acclaimed by many as the worlds greatest novel, Anna Karenina provides a vast panorama of contemporary life in Russia and of humanity in general. In it Tolstoy uses his intense imaginative insight to create some of the most memorable characters in all of literature. Anna is a sophisticated woman who abandons her empty existence as the wife of Karenin and turns to Count Vronsky to fulfil her passionate nature - with tragic consequences. Levin is a reflection of Tolstoy himself, often expressing the authors own views and convictions..',
  ),
  Book(
    image: 'https://francisboutle.co.uk/wp-content/uploads/2018/04/onegin-600x901.jpg',
    price: 12.50,
    rate: 4.10,
    pages: 240,
    published: 1833,
    title: 'Eugene Onegin',
    author: 'Alexander Pushkin',
    description: 'Eugene Onegin is the master work of the poet whom Russians regard as the fountainhead of their literature. Set in 1820s Russia, Pushkins verse novel follows the fates of three men and three women. Engaging, full of suspense, and varied in tone, it also portrays a large cast of othercharacters and offers the reader many literary, philosophical, and autobiographical digressions, often in a highly satirical vein. Eugene Onegin was Pushkins own favourite work, and this new translation conveys the literal sense and the poetic music of the original.',
  ),
  Book(
    image: 'https://th.bing.com/th/id/OIP.JYcK3hxLxiAbkd-grsC66AHaLX?rs=1&pid=ImgDetMain',
    price: 6.80,
     rate: 4.03,
    pages: 32 ,
    published: 1877,
    title: 'The Dream of a Ridiculous Man',
    author: 'Fyodor Dostoevsky',
    description: 'A short story by Fyodor Dostoyevsky written in 1877. It begins with a man walking St. Petersburgs streets while musing upon how ridiculous his life is, as well as its distinct lack of meaning or purpose. This train of thought leads him to the idea of suicide, which he resolves to commit using a previously-acquired gun. However, a chance encounter with a distressed little girl in the street derails his drastic plans.',
  ),
  Book(
    image: 'https://sevenov.com/wp-content/uploads/2023/02/the-overcoat-20230213-683x1024.jpg',
    price: 8.40,
     rate: 4.15,
    pages: 57 ,
    published: 1842,
    title: 'The Overcoat',
    author: 'Nikolai Gogol',
    description: 'The Overcoat which is generally acknowledged as the finest of Gogols memorable Saint Petersburg stories, is a tale of the absurd and misplaced obsessions.',
  ),
  Book(
    image: 'https://th.bing.com/th/id/OIP.xTzCeOBe5FsYjn8Rx7xilwHaNA?rs=1&pid=ImgDetMain',
    price: 13.75,
     rate: 4.26,
    pages: 353,
    published: 1939,
    title: 'Beware of Pity',
    author: 'Stefan Zweig',
    description: 'Hofmiller, an Austro-Hungarian cavalry officer stationed at the edge of the empire, is invited to a party at the home of a rich local landowner, a world away from the dreary routine of his barracks. The surroundings are glamorous, wine flows freely, and the exhilarated young Hofmiller asks his hosts lovely daughter for a dance, only to discover that sickness has left her painfully crippled. It is a minor blunder, yet one that will go on to destroy his life, as pity and guilt gradually implicate him in a well-meaning but tragically wrongheaded plot to restore the unhappy invalid to health.',
  ),
  Book(
    image: 'https://www.vanoorschot.nl/wp-content/uploads/2021/06/9789028202580_covr.jpg',
    price: 9.20,
     rate: 4.13,
    pages: 586 ,
    published: 1859,
    title: 'Oblomov',
    author: 'Ivan Goncharov',
    description: 'Even though Ivan Goncharov wrote several books that were widely read and discussed during his lifetime, today he is remembered for one novel, Oblomov, published in 1859, an indisputable classic of Russian literature, the artistic stature and cultural significance of which may be compared only to other such masterpieces as Nikolai Gogols Dead Souls, Leo Tolstoys Anna Karenina, and Fyodor Dostoevskys Brothers Karamazov. Stephen Pearls new translation, the first major English-language publication of Oblomov in more than fifty years, succeeds exquisitely to introduce this astonishing and endearing novel to a new generation of readers.',
  ),
  Book(
    image: 'https://th.bing.com/th/id/OIP.GMJvk60loD6RtNKUWBkjlQHaKc?rs=1&pid=ImgDetMain',
    price: 18.99,
    rate: 3.85,
    pages: 389,
    published: 1979,
    title: 'Flowers in the Attic',
    author: 'V.C. Andrews',
    description: 'Such wonderful children. Such a beautiful mother. Such a lovely house. Such endless terror! It wasnt that she didnt love her children. She did. But there was a fortune at stake—a fortune that would assure their later happiness if she could keep the children a secret from her dying father. So she and her mother hid her darlings away in an unused attic. Just for a little while. But the brutal days swelled into agonizing years. Now Cathy, Chris, and the twins wait in their cramped and helpless world, stirred by adult dreams, adult desires, served a meager sustenance by an angry, superstitious grandmother who knows that the Devil works in dark and devious ways. Sometimes he sends children to do his work—children who—one by one—must be destroyed.... Way upstairs there are four secrets hidden. Blond, beautiful, innocent struggling to stay alive....',
  ),
  Book(
    image: 'https://th.bing.com/th/id/OIP.xpAjIFwXgGtA8kwEMeThGAAAAA?rs=1&pid=ImgDetMain',
    price: 7.99,
     rate: 4.48,
    pages: 671 ,
    published: 1866,
    title: 'Martin Eden',
    author: 'Jack London',
    description: 'The semiautobiographical Martin Eden is the most vital and original character Jack London ever created. Set in San Francisco, this is the story of Martin Eden, an impoverished seaman who pursues, obsessively and aggressively, dreams of education and literary fame. London, dissatisfied with the rewards of his own success, intended Martin Eden as an attack on individualism and a criticism of ambition; however, much of its status as a classic has been conferred by admirers of its ambitious protagonist.',
  ),
  Book(
    image: 'https://i.pinimg.com/originals/fa/ee/0c/faee0c2f8b3b5975e4d4314c31e4dd3c.jpg',
    price: 19.49,
     rate: 4.48,
    pages: 496 ,
    published: 1936,
    title: 'Three Comrades',
    author: 'Erich Maria Remarque',
    description: 'The year is 1928. On the outskirts of a large German city, three young men are earning a thin and precarious living. Fully armed young storm troopers swagger in the streets. Restlessness, poverty, and violence are everywhere. For these three, friendship is the only refuge from the chaos around them. Then the youngest of them falls in love, and brings into the group a young woman who will become a comrade as well, as they are all tested in ways they can never have imagined. . . .',
  ),
  Book(
    image: 'https://th.bing.com/th/id/OIP.vehYWnZLs9p5O0UhKurmogAAAA?rs=1&pid=ImgDetMain',
    price: 15.30,
     rate: 4.43,
    pages: 464 ,
    published: 1945,
    title: 'Arch of Triumph',
    author: 'Erich Maria Remarque',
    description: 'It is 1939. Despite a law banning him from performing surgery, Ravic – a German doctor and refugee living in Paris – has been treating some of the city’s most elite citizens for two years on the behalf of two less-than-skillful French physicians.Forbidden to return to his own country, and dodging the everyday dangers of jail and deportation, Ravic manages to hang on – all the while searching for the Nazi who tortured him back in Germany. And though he’s given up on the possibility of love, life has a curious way of taking a turn for the romantic, even during the worst of times….',
  ),
];
