// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv8BED0M19CaVtGve9Uk_DVS3_dELKrdA',
    appId: '1:538773260439:web:97596aab1f0b8f9a8141d2',
    messagingSenderId: '538773260439',
    projectId: 'firebase-store123',
    authDomain: 'fir-store123.firebaseapp.com',
    storageBucket: 'firebase-store123.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATszbnZIoq5__JYHLrHSvrxLpnLSTDAXY',
    appId: '1:538773260439:android:2087549db99628f18141d2',
    messagingSenderId: '538773260439',
    projectId: 'firebase-store123',
    storageBucket: 'firebase-store123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdXcbZJK9EdQilLkGRUxJ1fpgD3wvldjg',
    appId: '1:538773260439:ios:42cd4cd62f46d8088141d2',
    messagingSenderId: '538773260439',
    projectId: 'firebase-store123',
    storageBucket: 'firebase-store123.firebasestorage.app',
    iosBundleId: 'com.example.bookStore',
  );
}
